#!/usr/bin/env python3
"""
Update manifest.yaml with current data hash and timestamp.

This script computes a SHA256 hash of all data files (excluding manifest.yaml)
to enable clients to detect when data has changed.
"""

import hashlib
import sys
from datetime import datetime, timezone
from pathlib import Path

import yaml


def compute_data_hash(data_dir: Path) -> str:
    """Compute SHA256 hash of all data files.

    Files are sorted by path to ensure deterministic ordering.
    The manifest.yaml itself is excluded from the hash.

    Args:
        data_dir: Path to the data directory.

    Returns:
        Hexadecimal SHA256 hash string.
    """
    hasher = hashlib.sha256()

    # Collect all data files (yaml and json), excluding manifest.yaml
    data_files: list[Path] = []
    for pattern in ["**/*.yaml", "**/*.json"]:
        data_files.extend(data_dir.glob(pattern))

    # Filter out manifest.yaml and sort for deterministic ordering
    data_files = sorted(
        f for f in data_files if f.name != "manifest.yaml"
    )

    for file_path in data_files:
        # Include relative path in hash so renames are detected
        rel_path = file_path.relative_to(data_dir)
        hasher.update(str(rel_path).encode("utf-8"))
        hasher.update(file_path.read_bytes())

    return hasher.hexdigest()


def update_manifest(manifest_path: Path, data_dir: Path) -> bool:
    """Update manifest.yaml with current hash and timestamp.

    Args:
        manifest_path: Path to manifest.yaml file.
        data_dir: Path to data directory.

    Returns:
        True if update was successful, False otherwise.
    """
    # Load existing manifest to check old hash
    old_hash = ""
    if manifest_path.exists():
        try:
            with open(manifest_path, encoding="utf-8") as f:
                manifest = yaml.safe_load(f) or {}
                old_hash = manifest.get("data_hash", "")
        except (IOError, yaml.YAMLError):
            pass

    # Compute new hash
    new_hash = compute_data_hash(data_dir)
    last_modified = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # Write updated manifest
    try:
        with open(manifest_path, "w", encoding="utf-8") as f:
            f.write("# MatDB Data Manifest\n")
            f.write("# This file is auto-generated by scripts/update_manifest.py\n")
            f.write("# Do not edit data_hash or last_modified manually.\n\n")
            f.write(f"data_hash: {new_hash}\n")
            f.write(f"last_modified: '{last_modified}'\n")

        if old_hash != new_hash:
            print("✓ Updated manifest.yaml:")
            print(f"  - Hash: {new_hash[:16]}...")
            print(f"  - Last modified: {last_modified}")
        else:
            print("✓ manifest.yaml is up to date (no data changes)")

        return True

    except IOError as e:
        print(f"Error: Failed to write {manifest_path}: {e}", file=sys.stderr)
        return False


def main() -> int:
    """Main entry point.

    Returns:
        Exit code: 0 on success, 1 on error.
    """
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    data_dir = project_root / "data"
    manifest_path = data_dir / "manifest.yaml"

    if not data_dir.exists():
        print(f"Error: {data_dir} not found", file=sys.stderr)
        return 1

    success = update_manifest(manifest_path, data_dir)
    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
